# Generated by Django 5.1.2 on 2024-10-28 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Укажите создателя бронирования', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Укажите № стола', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table', verbose_name='Стол'),
        ),
    ]
