# Generated by Django 5.1.2 on 2024-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(help_text='Укажите № стола', verbose_name='№ стола'),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(blank=True, help_text='Укажите к-во мест', null=True, verbose_name='К-во мест'),
        ),
    ]
