# Generated by Django 5.1.2 on 2024-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_table_number_alter_table_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, max_length=25, null=True, verbose_name='Дата и время брони'),
        ),
    ]
