# Generated by Django 5.1.2 on 2024-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_booking_slug_alter_booking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['name', 'description', 'datetime_booking', 'table'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='datetime_booking',
            field=models.DateTimeField(blank=True, max_length=25, null=True, verbose_name='Дата и время брони'),
        ),
    ]
