# Generated by Django 5.1.2 on 2024-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_options_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, help_text='Укажите активность брони', null=True, verbose_name='Активность брони'),
        ),
    ]
