# Generated by Django 5.1.2 on 2024-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_booking_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Активность брони'),
        ),
    ]
